### ISSUE TITLE
[Build] Error check failing 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-nsm#67]
**Description**
The error check build step is failing at https://github.com/layer5io/meshery-nsm/runs/644121144?check_suite_focus=true#step:4:20

**Comment by leecalcote** [comment]
@ashiscs do you mind having a look here?

**Comment by Aisuko** [comment]
As a result of https://github.com/layer5io/meshery-nsm/actions/runs/96816395 result. I believe We can close this issue.

Reference PR: #68 #69
